server:
  port: 8912

spring:
  application:
    name: nacos-order-api

  profiles:
    active: dev

#  redis:
#    database: 0 #Redis数据库索引，默认为0
#    host: 127.0.0.1
#    port: 6379
#    password: redis
#    jedis: #Jedis连接池配置
#      pool:
#        max-active: 10 #连接池最大活跃连接数，控制并发连接上限
#        max-wait: 1000 #获取连接的最大等待时间(毫秒)，超时将抛出异常
#        max-idle: 8 #连接池最大空闲连接数，保持的空闲连接上限
#        min-idle: 5 #连接池最小空闲连接数，保持的空闲连接下限
#    timeout: 1000 #redis操作超时时间(毫秒)，包括连接和读写超时


#  datasource:
#    url: jdbc:mysql://localhost:3306/vue3db?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMulti
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver #5版本之后替换为com.mysql.cj.jdbc.Driver

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.cloud.model

#logging:
#  level:
#    com.cloud.dao: debug
#    org.apache.ibatis: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl