server:
  port: 8184

spring:
  application:
    name: nacos-server

  cloud:
    nacos:
      discovery:
      server-addr: ${nacosCenter.hostName}:${nacosCenter.hostPort}
  security:
    user:
      name: admin
      password: 123456


nacosCenter:
  hostName: localhost
  hostPort: 8848

